async function deals_breakers(opt){switch(opt){case'coupons':deal_uri='';deal_title='COUPONS'
break;default:deal_uri='https://yazing.com/deals/'+opt;deal_title='NEW DEALS';}
$.get(deal_uri,function(html){ad_txt=[];ad_link=[];ad_coupon=[];coupon_txt=[];b=0;totrows=0;li_uni='';li_s='';logo_uri=$(html).find(".companyLogo img").attr('src');logo_desc=$(html).find(".companyDescription").text();deal_logo='<img src="'+logo_uri+'"/>';el_brands=$(html).find(".brand");el_brands.each(function(){totrows++;})
for(a=1;a<=totrows;a++){temp_a=$(el_brands[a]).find("a");temp_coupon=$(el_brands[a]).find(".coupontext");if(temp_a[0]){ad_txt[b]=$(temp_a[0]).text();ad_link[b]='https://yazing.com'+temp_a[0].pathname+'/drn';}else{ad_txt[b]='';ad_link[b]='';}
if(temp_coupon[0]){ad_coupon[b]=$(temp_coupon[0]).attr('data-clipboard-text');}
if(ad_coupon[b]){coupon_txt[b]='<div class="coupon_code"><span class="deal_ico"><i class="fas fa-cut"></i></span>'+ad_coupon[b]+'</div>';}else{coupon_txt[b]='';}
if(ad_txt[b])
li_s+='<a target="_blank" href="'+ad_link[b]+'"><h2><span class="deal_ico"><i class="fas fa-money-bill"></i></span>'+ad_txt[b]+coupon_txt[b]+'</h2></a>';b++;}
li_s+='<div style="line-height:450px;">&nbsp;</div>';li_uni='<div class="deals_wrap_header"><div class="deal_header_logo">'+deal_logo+'</div><div class="deal_header_title"><h1>'+deal_title+'</h1></div></div>';li_uni+='<div class="deals_wrap">'+li_s+'</div>';$('#wxy00').html(li_uni);});}
function openNav(){document.getElementById("myNav").style.width="100%";}
function closeNav(){document.getElementById("myNav").style.width="0%";}
async function proc_deals_breakers(brand){await deals_breakers(brand);myNav_width=parseInt($('#myNav').width());if(myNav_width>0){await closeNav();}}
$(document).ready(function(){$('.mn_btn').click(function(){openNav();})
$('#txt-search').keyup(function(){var searchField=$(this).val();if(searchField===''){$('#filter-records').html('');return;}
var regex=new RegExp(searchField,"i");var output='<div class="row">';var count=1;$.each(brandsX,function(key,val){if((val.id.search(regex)!=-1)||(val.name.search(regex)!=-1)){output+='<div>';output+='<div>';output+='<p onclick="proc_deals_breakers(\''+val.id+'\');">'+val.name+'</p>'
output+='</div>';output+='</div>';if(count%2==0){output+='</div><div class="row">'}
count++;}});output+='</div>';$('#filter-records').html(output);});});var ajax={};ajax.x=function(){if(typeof XMLHttpRequest!=="undefined"){return new XMLHttpRequest()}var a=["MSXML2.XmlHttp.6.0","MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0","Microsoft.XmlHttp"];var d;for(var b=0;b<a.length;b++){try{d=new ActiveXObject(a[b]);break}catch(c){}}return d};ajax.send=function(b,f,e,d,c){if(c===undefined){c=true}var a=ajax.x();a.open(e,b,c);a.onreadystatechange=function(){if(a.readyState==4){f(a.responseText)}};if(e=="POST"){a.setRequestHeader("Content-type","application/x-www-form-urlencoded")}a.send(d)};ajax.get=function(a,e,f,c){var d=[];for(var b in e){d.push(encodeURIComponent(b)+"="+encodeURIComponent(e[b]))}ajax.send(a+(d.length?"?"+d.join("&"):""),f,"GET",null,c)};ajax.post=function(a,e,f,c){var d=[];for(var b in e){d.push(encodeURIComponent(b)+"="+encodeURIComponent(e[b]))}ajax.send(a,f,"POST",d.join("&"),c)};document.currentScript=document.currentScript||(function(){var a=document.getElementsByTagName("script");return a[a.length-1]})();function getScriptURL(){var a=document.currentScript||document.querySelector('script[src*="showdeals-yzwg.js"]');return a.src}function getURLParameter(a){return decodeURI((RegExp(a+"=(.+?)(&|$)").exec(getScriptURL())||[,null])[1])}ajax.post("https://yazing.com/widget/ajax-show-deals",{username:"drn",brandList:brandsF,displayType:"image",displayAvatar:"0",title:"<span style='color:white;'>Feature Brands</span>",subtitle:"",footerTopdeals:"",elementId:"yzwg-796f1f31fc92e56317b7cae9e4b91a86",url:document.URL},function(b){var a=JSON.parse(b);if(a.elementId!==""){json_content=$(a.content).find("a");$(json_content).each(function(c,d){$(d).attr("href","#");$(d).attr("target","_self");$(d).attr("id",brandsF[c]);$(d).attr("onclick","return proc_deals_breakers(this.id);")});$("#"+a.elementId).html(json_content);$("#"+a.elementId).append('<div style="line-height:450px;">&nbsp;</div>')}});